spring:
  application:
    name: order-service
<<<<<<< HEAD
    
=======
  rabbitmq:
    host: 192.168.242.131
    port: 5672
    username: admin
    password: admin  
>>>>>>> branch 'master' of https://github.com/ddxieluenyan/sp-config.git
# server:
#  port: 8201
  
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
---
spring:
  profiles: order1
  
server:
  port: 8201
  
---
spring:
  profiles: order2
  
server:
  port: 8202